/*
 * 
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.


Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"

 */

package com.Problems;

public class Find_the_Difference {

	public static void main(String[] args) {
		String s = "abcd";
		String t = "abcde";
		System.out.println(findTheDifference(s, t)); // Output: e

	}

	private static char findTheDifference(String s, String t) {
		char res = 0;

		for (char c : s.toCharArray())
			res ^= c;

		for (char c : t.toCharArray())
			res ^= c;
		return res;
	}

	// OR

//	private static char findTheDifference(String s, String t) {
//		int resS = 0, resT = 0;
//		for (char c : s.toCharArray())
//			resS += c;
//		for (char c : t.toCharArray())
//			resT += c;
//		return (char) (resT - resS);
//	}

}
